---
- hosts: all
  sudo: true
  vars_files:
    - box/definition.yml
  roles:
    - server
    - vagrant_local
    - apache
    - mysql
    - php
    - xdebug
    - composer
    - symfony_installer
    - app
